openworm/org.geppetto.frontend

src/main/webapp/js/components/app.js
When sim parameter is sent in the url, before loading the simulation, now, we checked the dom is ready. Otherwise, random errors may appear because, for instance, the console hasn't been loaded yet.
=> Console element bug

src/main/webapp/js/GEPPETTO.Resources.js, src/main/webapp/js/nodes/EntityNode.js, src/main/webapp/js/widgets/connectivity/Connectivity.css, src/main/webapp/js/widgets/connectivity/Connectivity.js, src/main/webapp/js/widgets/treevisualiser/treevisualiserd3/TreeVisualiserD3.css
@adrianq @jrmartin made some improvements to the connectivity widget, now the labels are gone (too small to be meaningful in any big network) and have been replaced by a single label which gets updated on mouse hover. Also now clicking on a square will select the two connected entities. 
@jrmartin I have removed unselectAll from the select method for an Entity node so that it is possible to select more than one entity. The connecting lines are still visible for both selected entities though which makes it messy. When I do multiple selection from the connectivity widget I'm manually hiding them but what I think should happen if more than one entity is selected is that only connection lines between all the selected entities are visualized but I haven't made those change yet.
=> Connectivity widget improvements

src/main/webapp/js/GEPPETTO.Init.js
Hello,
This is my first attempt at a contribution so definitely please let me know if you'd like me to change anything.
It's a small change to GEPPETTO.Init.js to address issue #34. It forces reuse of the WebGL context. I'm not sure why reusing the context causes camera displacement on Chrome OSX.
On my machine (Retina MacBook Pro) the displacement happens after the 3rd scene load. And then the camera displaces more after each subsequent scene load.
Please let me know if you have any questions or if you'd like me to make any changes.
Thanks!
David Frenkiel
=> Issue #34: Changed WebGL renderer to a singleton to resolve camera displacement issue on Chrome OSX.

src/main/webapp/js/widgets/buttonBar/ButtonBar.js, src/main/webapp/js/widgets/connectivity/Connectivity.css, src/main/webapp/js/widgets/connectivity/Connectivity.js
- fixed opening multiple widgets simultaneously
- fixed sorting for multiple conn matrices
- fixed a lot of other things I don't remember anymore
- most important: no more domain hardcoded properties (line widths / colours / node colours can be mapped to anything) - all done through {options}. 
- Examples using the conn widget will have to be updated.
=> Many improvements to the connectivity widget

src/main/java/org/geppetto/frontend/controllers/Login.java
@tarelli Redirection response for webservice calls using CORS are not allowed for Safari. This causes OSB not to work properly in Safari. I have added a new parameter that can be used to define which type of answer you are expecting from the webservice. If this parameter is not passed the logout webservice works as usual.
=> Added json as an available output format for logout webservice

src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java, src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java, src/main/java/org/geppetto/frontend/messages/InboundMessages.java, src/main/webapp/js/GEPPETTO.Main.js
We were having an exception in Geppetto from time to time because we try to close a project server side but actually the project was already closed. Many wise men from all around the world have tried to find an answer for this phenomenon. Finally, the mystery has been disclosed: we close the project when there is a prolonged inactivity and we close it again when the user leave the page, close the tab, the browser, etc... The first one is done on purpose but the second one is an event automatically triggered because of the socket disconnection. When the code in charged of dealing with the second event tries to remove the project from the project list server side and exception was raised as the project couldn't be found server side.
The solution implemented is to actually not only close the …
=> Fix Close Project Exception

.travis.yml
@tarelli this seems to solve it.  [Now the failure](https://travis-ci.org/openworm/org.geppetto.frontend/builds/148927932) is not about the travis-install.sh script being missing but something else.  Unclear why it was working fine before and now it stopped working with no changes.  Maybe something subtle on travis' backend??  
(PR to the wrong branch last time)
=> trying to get the travis script to run

pom.xml
use `mvn site` to get the jsdocs built now.  speeds up regular builds
=> change docs build from install to site

src/main/webapp/js/components/interface/tree/Tree.js
- By default, clicking on a node the node toggles visibility of his children. This behaviour can be overwritten if handleClick property is passed.
- Fix expand/collapse all functions
- Minor clean up
=> Tree Component Improvement

src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java, src/main/webapp/js/geppettoProject/ExperimentsController.js
see also: https://github.com/openworm/org.geppetto.simulation/pull/131
this fixes issue with OSB sample projects having their experiment state written (since they are persisted, see comodl because osb.org has a temporary fix in place; for example every time you open HH there are more popups because the script runs, and the ones from before have been saved)
=> add write permissions check

src/main/webapp/js/components/interface/carousel/Carousel.js
- Minor fix on constructor so settings are properly passed.
- Fix for the carousel to display properly. Carousel layout was not looking properly on init because it was calculated based on the initial parent container. As we are manipulating the dom from different sides it was not properly recalculated. A forceupdate on componentdidmount makes the trick. Now it works properly when it is a regular component or a component inside a jquery dialog.
=> Carousel Fixes

src/main/webapp/js/geppettoProject/model/SimulatorConfiguration.js
if timestep or length params modified in exp table then the expt run form won't validate as they become set as strings rather than floats
=> fix run bug when setting params from exp table

src/main/webapp/js/pages/geppetto/GEPPETTO.Flows.js
this fixes the error but Play still doesn't do what I expect: it more or less does nothing for me (graphs don't animate, pause/stop don't become enabled etc). trying to trace this through has not been very illuminating because none of the code seems to have changed recently and I think it's fairly obvious that in 74a7170 I've merely restated what was there before.
=> handle promise on play button

src/main/webapp/js/components/widgets/plot/Plot.js
Unit throws `SyntaxError: Unit "UnitValue" not found`. when SI Unit is not found.
This pull request will catch this excpetion and save unit as an empty string.
=> fix unit throw exception error

src/main/webapp/js/communication/geppettoJupyter/PythonControlledCapability.js
this will be needed for CNS. Basically it deals with: 
- float fields been filled up with text,
- fields that end up with a value equal to an empty string,
- fields that must contain a default value for netpyne to work.
**PythonControlledCapability.js** should not contain things like this one: 
` Utils.execPythonCommand('del netpyne_geppetto.' + this.props.model)`
but we need to rethink how to deal with error messages and fields completed with the wrong type. I am opening a Trello Card for this topic.
- try to enter a string in a textfield (an alert will appear)
- fill a field with some value and then check with `print(netpyne_geppetto.netParams.popParams['cellType'])`. the value that you entered. Then proceed to delete the field and type the previous command again. (the key should not …
=> fix type format error

src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js
prevents returning 'null' in floatover
- [N/A] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
=> HotFix: null passing fix for labels

src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js
Resolves a previously missed issue with unlabelled neuropil (previously didn't happen) in L3 template being returned over actually labelled neuropil giving the impression we didn't have labelled content.
Note: This probably warrants quick integration rather than waiting for the float over improvements.
=> Quick fix to ignore null results

src/main/webapp/js/communication/MessageSocket.js
Need to trigger GEPPETTO.Events.Websocket_disconnected when severed by external actors.
Ref https://github.com/VirtualFlyBrain/geppetto-vfb/issues/290
=> handling external severing of connection.

src/main/webapp/js/pages/geppetto/GEPPETTO.Main.js, src/main/webapp/package.json
url-join behaviour:
urljoin('wss:', "geppetto") = 'wss://geppetto'
urljoin('wss:/', "geppetto") = 'wss://geppetto'
urljoin('wss://', "/geppetto") = 'wss://geppetto'
urljoin('wss://', "//geppetto") = 'wss://geppetto'
urljoin('wss', "geppetto") = 'wss/geppetto'    <---- without ":"  
urljoin('wss//', "/geppetto") = 'wss/geppetto'
=> use url-join for host in message.socket.connect

src/main/webapp/webpack.config.js
Casper Tests are passing locally for contextPath = "/" and contextPath = "org.geppetto.frontend"
mvn does not require additional configuration.
Unfortunately, geppetto.ejs is still sensitive to the way we specify contextpath:
line 16
`<base href="<%=htmlWebpackPlugin.options.GEPPETTO_CONFIGURATION.contextPath%>" />`
=> fix typo in publicPath
