openworm/org.geppetto.frontend

src/main/webapp/js/widgets/connectivity/Connectivity.js
=> Fixes destruction of preexisting conn matrix upon creation of a new one.

src/main/webapp/js/widgets/connectivity/Connectivity.css, src/main/webapp/js/widgets/connectivity/Connectivity.js
Probably useless in its present form, need to consult (and maybe do some psychophysics...) users.
=> Added initial support for Chord Plots.

src/main/webapp/js/widgets/Widget.css, src/main/webapp/js/widgets/Widget.js
- setDraggable(true/false)
- showExitButton(true/false)
- setClass(className) <-- used by setDraggable but can also be used for on the fly customization
@tarelli @adrianq can one of you have a quick look at the code and merge?
Tested on Chrome and Firefox.
=> added some features to widgets

Gruntfile.js, pom.xml, src/main/webapp/WEB-INF/web.xml, src/main/webapp/dashboard/js/main.js, src/main/webapp/dashboard/js/views/dashboard/DashboardView.js, src/main/webapp/dashboard/js/views/projects/ProjectDetailsView.js, src/main/webapp/dashboard/templates/projects/projectDetailsTemplate.hbs, src/main/webapp/templates/dashboard.vm, src/main/webapp/templates/dist/dashboard.vm, src/main/webapp/templates/dist/geppetto.vm, src/main/webapp/templates/geppetto.vm
@tarelli This PR implements a grunt profile for geppetto when working as an embedded website. I have refactored a bit the grunt stuff and fix the development profile.
mvn install -P master
This profile is specific for production environments. It compresses, uglifies and everything the js code as usual. However now you can [pass up to 4 parameters](https://github.com/openworm/org.geppetto.frontend/blob/70902254e36ee16b54db4d148f1ce5d4597ceb7e/pom.xml#L15-L20). If no arg is sent, it uses the value by default. Some examples:
- mvn install -P master -> It works as usual.
- mvn install -P master "-Dembedded=true" "-DuseSsl=false" -> It works as usual, it doesn't use ssl and change some code (see paragraph below for what code is changed) in order to make it suitable for an embedded environment. …
=> Embedded environment

src/main/webapp/WEB-INF/web.xml
@tarelli If you can merge it for this release it would be great. Any question/comment/issue let me know. Cheers!
=> Implement CORS for embedded environment

src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java, src/main/java/org/geppetto/frontend/messaging/DefaultMessageSender.java, src/main/java/org/geppetto/frontend/messaging/MessageSender.java, src/main/webapp/js/websocket-handlers/GEPPETTO.MessageSocket.js
This is just a very minor refactoring of the message sender code that delivers experiment files to the browser.
=> Issue #309: A little refactoring of the message sender

src/main/webapp/js/nodes/VisualGroupNode.js, src/main/webapp/js/widgets/treevisualiser/treevisualiserdat/TreeVisualiserDAT.js
- Multiple widgets don't break it anymore
- We don't show infinity label anymore
- We don't show colour span for visual group node when it is not needed
- Some code refactor
=> Fix tree visualiser widget for visual tree

src/main/webapp/js/GEPPETTO.js
See card #254 for further information
=> Fix js errors when Geppetto is working as an embedded website

.gitignore, src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java, src/main/webapp/dashboard/js/libs/jquery/jqueryui/jquery-ui-1.8.3.min.js, src/main/webapp/dashboard/js/libs/require/require.js, src/main/webapp/dashboard/js/views/dashboard/DashboardView.js, src/main/webapp/js/3d_visualization/GEPPETTO.SceneController.js, src/main/webapp/js/GEPPETTO.Init.js, src/main/webapp/js/GEPPETTO.Resources.js, src/main/webapp/js/GEPPETTO.js, src/main/webapp/js/geppetto-objects/G.js, src/main/webapp/js/nodes/RuntimeTreeController.js, src/main/webapp/js/vendor/ColladaLoader.js, src/main/webapp/js/vendor/JSXTransformer.js, src/main/webapp/js/vendor/THREEx.KeyboardState.js, src/main/webapp/js/vendor/TrackballControls.js, src/main/webapp/js/vendor/jquery-1.9.1.js, src/main/webapp/js/vendor/jquery-ui-1.10.3.custom.js, src/main/webapp/js/vendor/react.js, src/main/webapp/js/websocket-handlers/GEPPETTO.SimulationHandler.js, src/main/webapp/js/widgets/Widget.js, src/main/webapp/less/bootstrap/normalize.less, src/main/webapp/r.js
Absolute camera movement, solves issue openworm/org.geppetto#160
=> Absolute camera movement.

src/main/webapp/js/3d_visualization/GEPPETTO.SceneController.js, src/main/webapp/js/nodes/NodeFactory.js, src/main/webapp/js/nodes/VisualGroupNode.js
- Allows folder inside visualisation tree
- Allows highlighting individual cylinders (we were already highlightining visual groups)
=> Inhomogeneous channel 

src/main/webapp/js/widgets/connectivity/matrices.js
Fixed sorting. Nice catch, @tarelli .
=> fixed matrix sorting

src/main/webapp/js/widgets/connectivity/chords.js
fixes https://github.com/openworm/org.geppetto.frontend/issues/389
=> Removing ES6 specific features

src/main/webapp/js/widgets/connectivity/chords.js
- legend
- tooltips when hovering over slices
- removed unused logic (previously used to represent disconnected fraction of cells in pops, which does not make much sense in the current version which concerns number of connections)
=> Improvements to Chord layout

src/main/webapp/js/components/dev/help/HelpModal.js
=> Added extra help functionality

README.md, src/main/webapp/dashboard/templates/projects/projectDetailsTemplate.hbs
Add hyperlinks to muscle memory (and other project) descriptions.
=> Muscle memory fix

README.md, src/main/webapp/js/components/dev/help/HelpModal.js, src/main/webapp/less/components/modal/help-modal.less
Adding improved help with colour coding for each of the different experiment representations.
=> Improved help

Gruntfile.js, pom.xml, src/main/java/org/geppetto/frontend/controllers/Application.java, src/main/java/org/geppetto/frontend/tests/Test.java, src/main/java/org/geppetto/frontend/tests/TestFeatures.java, src/main/java/org/geppetto/frontend/tests/TestModel.java, src/main/java/org/geppetto/frontend/tests/TestModule.java, src/main/webapp/js/GeppettoNeuronalCustomTests.js, src/main/webapp/js/tests/QUnitNeuronalCustomTests.js, src/main/webapp/templates/GeppettoCoreTests.vm, src/main/webapp/templates/GeppettoFluidDynamicsTests.vm, src/main/webapp/templates/GeppettoNeuronalCustomTests.vm, src/main/webapp/templates/GeppettoNeuronalTests.vm, src/main/webapp/templates/GeppettoPersistenceTests.vm, src/main/webapp/templates/dist/GeppettoCoreTests.vm, src/main/webapp/templates/dist/GeppettoNeuronalCustomTests.vm, src/main/webapp/templates/dist/GeppettoNeuronalTests.vm, src/main/webapp/templates/dist/GeppettoPersistenceTests.vm, src/main/webapp/templates/dist/geppetto.vm, src/main/webapp/templates/dist/tests.vm
@tarelli to be discussed... not to be merged yet :)
=> Custom tests infraestructure

src/main/webapp/js/widgets/connectivity/Connectivity.js
Double click over connectivity layout button now applies layout and closes modal.
=> Conn w config gui patch

src/main/webapp/js/tests/casperjs/geppetto-tests.js
=> Travis docker

src/main/webapp/js/3d_visualization/GEPPETTO.SceneController.js, src/main/webapp/js/components/ComponentsInitialization_OSB.js, travis-install.sh
Makes the threshold for lines 20000 so more reasonably sized models will render as cylinders
Computes a "rainbow" colouring for cells as func of intensity: dark blue@-70mV -> blue-> green-> red at 30mV
Change to travis.yml so branches build with development by default
@tarelli
=> Changes for OSB live Janelia release

src/main/webapp/js/components/dev/ExperimentsTable/ExperimentsTable.js, src/main/webapp/js/model/AVisualCapability.js
also minor bug fix for 'undefined' deselection message
=> Add confirm dialog to Delete experiment button (fixes #538)

src/main/webapp/js/GEPPETTO.Events.js, src/main/webapp/js/components/dev/spotlight/spotlight.js
spotlight load event required for features in geppetto-osb.
=> add spotlight load event + remove domain specific code

src/main/webapp/js/GEPPETTO.Resources.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoCommonLibrary.json, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterModelSync.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterWidgetSync.js, src/main/webapp/js/model/ADerivedStateVariableCapability.js, src/main/webapp/js/model/ModelFactory.js, src/main/webapp/js/widgets/plot/Plot.js
- Polish Space Plot
- Create DerivedStateVariable
- Fix geometry radius
- Use type instead of anonymous type for main model variable
- Remove time hardcodes on plot widget
- Improve streaming in plot widget for x variable different to time
=> Space plot

src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterGUISync.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterWidgetSync.js, src/main/webapp/js/widgets/Widget.js
- Implement effect api for widgets
- Add api for shake effect to geppetto jupyter
=> Jquery ui effects

src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterGUISync.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterWidgetSync.js, src/main/webapp/js/widgets/plot/Plot.js
- Trigger onclose for panel and widget sync if panel is closed
- Implement non-resizable parent panels
- Remove hardcoded time on x axis
=> Window handling improvements

src/main/webapp/js/3d_visualization/GEPPETTO.SceneController.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterModelSync.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterWidgetSync.js, src/main/webapp/js/geppetto-objects/G.js, src/main/webapp/js/model/ObjectWrapper.js, src/main/webapp/js/model/VisualGroupElement.js
- Implement show for visualgroupelement
- Add visual groups to geppetto jupyter
- Bug fixing
=> Highlight section

src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterModelSync.js, src/main/webapp/js/components/geppetto-jupyter/GeppettoJupyterWidgetSync.js, src/main/webapp/js/websocket-handlers/GEPPETTO.SimulationHandler.js, src/main/webapp/js/widgets/plot/Plot.js
- Better legend management for plot widget
- Add API to override existing instance
- Fix axis recalculation for plots
=> Jupyter bug fixing and improvements

.travis.yml, src/main/webapp/package.json
@tarelli This should fix prod build..
=> remove eval for prod

src/main/webapp/webpack.config.js
@tarelli This should remove react prod warning. Let me know...
[Explanation](http://stackoverflow.com/questions/22118915/how-to-turn-on-off-reactjs-development-mode) and [Explanation 2](https://github.com/facebook/react/issues/6479)
=> set environment variable for node

src/main/webapp/js/components/interface/controlPanel/controlpanel.js
=> fix recorded variables shown in control panel after experiment complete

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
fixes https://github.com/openworm/org.geppetto/issues/519#issuecomment-308078354
=> keep colors when switching geometry types

src/main/webapp/extensions/extensionsConfiguration.json, src/main/webapp/js/components/interface/experimentsTable/ExperimentsTable.js, src/main/webapp/js/components/widgets/connectivity/Connectivity.js, src/main/webapp/js/pages/tests/casperjs/CoreTests.js, src/main/webapp/js/pages/tests/casperjs/CoreTestsUtility.js, src/main/webapp/js/pages/tests/casperjs/UITests.js
=> Tool tip fix

src/main/webapp/extensions/extensionsConfiguration.json
=> set default extension

src/main/webapp/js/pages/tests/casperjs/CoreTestsUtility.js, src/main/webapp/js/pages/tests/casperjs/UITests.js
switches default port for casper testing to 8080
=> default port for casper testing 8080

src/main/webapp/js/components/interface/3dCanvas/Canvas.js, src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
eg. https://github.com/mattearnshaw/NeuroMLTesting/blob/master/CElegans/pythonScripts/c302/examples/temp_test/c302_C1_Muscles.net.nml#L771
requires radius branch of model.neuroml (see pull request https://github.com/openworm/org.geppetto.model.neuroml/pull/129)
=> read radius from neuroml file

src/main/webapp/js/common/GEPPETTO.ViewController.js, src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterGUISync.js, src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterModelSync.js, src/main/webapp/js/components/ComponentFactory.js, src/main/webapp/js/components/controls/panel/Panel.js, src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js, src/main/webapp/js/components/interface/controlPanel/controlpanel.js, src/main/webapp/js/components/widgets/AWidget.js, src/main/webapp/js/components/widgets/Widget.js, src/main/webapp/js/pages/geppetto/geppetto.ejs, src/main/webapp/package.json, src/main/webapp/webpack.config.js
=> Development jupyter

src/main/webapp/js/pages/tests/casperjs/CoreTests.js, src/main/webapp/js/pages/tests/casperjs/CoreTestsUtility.js
=> test color of more instances

.travis.yml
@tarelli A one line change removing a script call that was only supposed to be there for debugging
=> Change casperjs port

src/main/webapp/js/components/AComponent.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewer.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewerUtils.js, src/main/webapp/js/components/widgets/WidgetCapability.js
- Better event handling in dicomviewer
- Allows to add custom icons
- Fix get container for components added in a react way
- Add full size for 3d view in dicomviewer
- Disable pan in dicom viewer
- Better image and helper localiser fitting
=> Mri refinements

src/main/webapp/js/components/interface/3dCanvas/Canvas.js, src/main/webapp/js/components/interface/bigImageViewer/BigImageViewer.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewer.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewer.less, src/main/webapp/js/components/interface/gallery/Gallery.js, src/main/webapp/js/components/interface/gallery/Gallery.less, src/main/webapp/js/components/interface/htmlViewer/HTMLViewer.js, src/main/webapp/js/components/interface/overlay/Overlay.js, src/main/webapp/js/components/interface/overlay/Overlay.less, src/main/webapp/js/components/interface/tree/Tree.js, src/main/webapp/js/components/interface/tree/Tree.less, src/main/webapp/js/components/widgets/WidgetCapability.js
Pass some extra properties to the components
=> Enhance html viewer & overlay

src/main/webapp/js/components/interface/gallery/Gallery.js, src/main/webapp/js/components/interface/gallery/Gallery.less, src/main/webapp/js/components/interface/htmlViewer/HTMLViewer.js, src/main/webapp/js/components/interface/overlay/Overlay.js, src/main/webapp/js/components/interface/tree/Tree.less
- Remove all icons except download and close
- Go straight to full size
- Reduce opacity for background
- Unmount gallery on close
- Create gallery in a declarative way
=> Gallery refinements

src/main/webapp/js/components/interface/dicomViewer/DicomViewer.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewer.less, src/main/webapp/js/components/interface/gallery/Gallery.js, src/main/webapp/js/components/interface/gallery/Gallery.less, src/main/webapp/js/components/interface/htmlViewer/HTMLViewer.js, src/main/webapp/js/components/interface/overlay/Overlay.js, src/main/webapp/js/components/interface/tree/Tree.less
Just some minor bug fixing. Should go after #660 and #659
=> Gallery dicom viewer refinements

src/main/webapp/js/components/interface/bigImageViewer/BigImageViewer.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewer.js, src/main/webapp/js/components/interface/dicomViewer/DicomViewer.less, src/main/webapp/js/components/interface/gallery/Gallery.js, src/main/webapp/js/components/interface/gallery/Gallery.less, src/main/webapp/js/components/interface/htmlViewer/HTMLViewer.js, src/main/webapp/js/components/interface/overlay/Overlay.js, src/main/webapp/js/components/interface/overlay/Overlay.less, src/main/webapp/js/components/interface/tree/Tree.js, src/main/webapp/js/components/interface/tree/Tree.less, src/main/webapp/js/components/widgets/WidgetCapability.js
Some minor changes and improvement for both widgets. There is an attempt to move widget button to the widget toolbar. Will look into that in a different PR.
=> big image and dicom viewer fixes

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js, src/main/webapp/js/components/interface/simulationControls/HelpModal.js
for models using the `connectionWD` tag (at least I think this is the root), such as [OpenCortex/ACNet](http://comodl.org/projects/opencortex/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FOpenCortex%252Fmaster%252Fexamples%252FACNet.net.nml), connections are displayed incorrectly. For example, you can see pyramidal cells appear to connect to themselves in [OpenCortex/ACNet](http://comodl.org/projects/opencortex/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FOpenCortex%252Fmaster%252Fexamples%252FACNet.net.nml).
I've slightly refactored and now everything should be good (it's already on live because I was testing on [this](http://opensourcebrain.org/projects/multiscale/models?explorer=https%253A%252F%252Fraw.gith …
=> Connections

src/main/webapp/js/components/widgets/AWidgetController.js, src/main/webapp/js/components/widgets/Widget.js
=> arrows fix

src/main/webapp/js/components/widgets/variablevisualiser/controllers/VariableVisualiserController.js
=> Promises w VariableVisualizer

src/main/webapp/js/components/interface/tutorial/Tutorial.js, src/main/webapp/js/components/widgets/Widget.js
=> updates from Vfb 8/17

src/main/webapp/js/components/interface/tutorial/Tutorial.js
=> minor fix from Vfb 8/17

src/main/webapp/js/components/interface/tutorial/Tutorial.js, src/main/webapp/js/components/widgets/Widget.js, src/main/webapp/js/components/widgets/WidgetCapability.js
=> fixes from Vfb 8/17

src/main/webapp/js/components/interface/dicomViewer/DicomViewerUtils.js, src/main/webapp/js/pages/tests/casperjs/PersistenceTests.js
=> Keeping up to date with Development

src/main/webapp/js/components/widgets/plot/Plot.js
this is required for colorbar plots
=> add plotly heatmap component (for colorbar)

src/main/webapp/js/components/widgets/Widget.js, src/main/webapp/js/components/widgets/WidgetCapability.js, src/main/webapp/js/components/widgets/plot/Plot.js
Fix for https://github.com/VirtualFlyBrain/geppetto-vfb/issues/21
=> fix from Vfb 8/17

src/main/webapp/package.json
=> onchange scripts that works with chunks (Much much faster)

.travis.yml, src/main/webapp/js/components/ComponentFactory.js, src/main/webapp/js/components/widgets/popup/Popup.js, src/main/webapp/js/components/widgets/treevisualiser/treevisualiserdat/controllers/TreeVisualiserControllerDAT.js, src/main/webapp/js/pages/tests/casperjs/PersistenceTests.js
=> Persistence fix

src/main/webapp/js/pages/tests/casperjs/CoreTests.js, src/main/webapp/js/pages/tests/casperjs/CoreTestsUtility.js
Fixed formatting in two changed files.
Added 'roundPlus' function.
Added rounding of camera position values.
- [*] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
- [*] Make sure both push and pr travis builds are passing before asking for a review
=> Test fix. Changes:

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
=> Shading patch

src/main/webapp/extensions/geppetto-default/ComponentsInitialization.js
=> Disable local storage for default extension

src/main/webapp/js/common/GEPPETTO.ViewController.js
=> fix glitch with setViews

src/main/webapp/extensions/geppetto-default/ComponentsInitialization.js
=> ViewController patch

src/main/java/org/geppetto/frontend/controllers/Application.java
=> fix 500 error when first loading page

src/main/java/org/geppetto/frontend/controllers/Application.java, src/main/webapp/js/common/GEPPETTO.ViewController.js
=> update to match Development

src/main/webapp/package.json
Ref #731
- [ NA ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
=> avoiding issues with version 0.28.8 of css-loader

src/main/webapp/js/components/widgets/stackViewer/StackViewer.js
- [NA] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
=> Fix to handle an already deleted instance in stack viewer

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
This is deployed on OSB.org, can be compared to original on comodl.
references
https://github.com/mrdoob/three.js/issues/568
https://github.com/openworm/org.geppetto.frontend/issues/724#issuecomment-355551359
=> remove CopyShader (fixes #724)

src/main/webapp/js/communication/MessageHandler.js, src/main/webapp/js/components/controls/modals/InputModal.js, src/main/webapp/js/components/controls/modals/ModalFactory.js, src/main/webapp/js/components/interface/form/Form.js, src/main/webapp/js/pages/dashboard/templates/projects/projectDetailsTemplate.hbs, src/main/webapp/js/pages/geppetto/G.js
More stuff... this is working with https://github.com/OpenSourceBrain/geppetto-osb/commit/6174d4b3bf3becfaea2243b96252467e84a9e7ab#diff-7e494ee04227a4cb5fb4f5766357ab29R178
=> add form option to input modal

src/main/webapp/js/components/widgets/connectivity/controllers/ConnectivityController.js
cf. [PlotsController.js#L36](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/components/widgets/plot/controllers/PlotsController.js#L36) etc.
=> fix bug preventing multiple connectivity widgets

src/main/webapp/js/components/interface/3dCanvas/Canvas.js, src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
=> add wrapper for showAxis

src/main/webapp/js/components/widgets/Widget.js, src/main/webapp/js/components/widgets/popup/Popup.js
=> fix showTitleBar and add showHistoryBar for saved widget state

src/main/webapp/js/components/widgets/plot/Plot.js
this fixes the issue noted here (second point) https://github.com/OpenSourceBrain/geppetto-osb/issues/97
"HH example -> [Model Desc ->] Na channel -> plot alpha_m: empty plot canvas due to `Uncaught (in promise) TypeError: Unsupported type of condition "Array"`"
=> fix activation variable plotting for certain expressions

src/main/webapp/package.json
=> bump jquery ui version

.travis.yml, src/main/webapp/js/pages/tests/casperjs/CoreTests.js, src/main/webapp/js/pages/tests/casperjs/CoreTestsUtility.js
=> test plot widgets graph contents

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
=> Modified spheres should be selectable

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js, src/main/webapp/js/pages/tests/casperjs/DefaultProjectsTests.js, src/main/webapp/js/pages/tests/casperjs/NeuronalTestsLogic.js, src/main/webapp/js/pages/tests/casperjs/utilities/TestsUtility.js
=> Cylinder fix

src/main/webapp/js/components/interface/3dCanvas/ColorController.js, src/main/webapp/js/geppettoModel/ModelFactory.js
=> Performance

.travis.yml, src/main/webapp/js/pages/tests/casperjs/GeppettoModelTests.js, src/main/webapp/js/pages/tests/casperjs/utilities/TestsUtility.js
=> Caspers qunit

src/main/webapp/extensions/geppetto-default/ComponentsInitialization.js
=> add save and share button for testing purposes

src/main/webapp/js/pages/tests/casperjs/NeuronalTestsLogic.js
=> fix cylinder test

src/main/webapp/js/pages/tests/casperjs/NeuronalTestsLogic.js
=> Removed tree visualizer from sample

src/main/webapp/js/components/interface/console/Console.js
=> Fix text, help is gone

src/main/webapp/js/communication/geppettoJupyter/PythonControlledCapability.js
=> support dict types

src/main/webapp/js/components/interface/query/query.js
should prevent warning messages in chrome
=> suggest adding passive to click event on slick image slider

.travis.yml, src/main/webapp/js/components/controls/iconButton/IconButton.js, src/main/webapp/js/pages/tests/casperjs/UIComponentsTests.js
=> Allow to assign IconButton id

src/main/webapp/js/communication/GEPPETTO.GlobalHandler.js, src/main/webapp/js/pages/tests/casperjs/UIComponentsTests.js
=> Casper tests

src/main/webapp/js/components/interface/3dCanvas/ColorController.js, src/main/webapp/js/components/widgets/plot/Plot.js
=> Analysis + Color

src/main/webapp/js/geppettoProject/ProjectsController.js, src/main/webapp/js/pages/tests/casperjs/UIComponentsTests.js
=> Test fix patch

src/main/webapp/package.json
=> change strategy to source-map

src/main/webapp/package.json
=> Griddle Update version

src/main/webapp/js/components/widgets/plot/Plot.js
=> fix analysis add/remove

src/main/webapp/js/components/interface/tree/Tree.js
=> Allows selection on parent folder in tree component

src/main/webapp/js/communication/geppettoJupyter/PythonControlledCapability.js
=> allows parsing string dict

src/main/webapp/js/communication/geppettoJupyter/PythonControlledCapability.js
This requires:
https://github.com/Neurosim-lab/netpyne/pull/329
some fields such as convergency, divergency, probability, etc, allow the user to enter a function in string form. 
If the metadata **type** is declared as *func*, the code will check that the string can be converted to lambda function. Otherwise it will show an error message on the Botton of the text field.
=> allow function as input in textFields

src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java, src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java, src/main/webapp/js/common/Manager.js, src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js, src/main/webapp/js/geppettoModel/model/Datasource.js
- connectorHandler and webSocket changed to accept array of strings.
- Manager.js and Datasource.js modified to send an array of strings.
- Stackviewer widget safe check for call back function.
=> Loading Mechanism feature: fetch variables batch

src/main/webapp/js/components/interface/query/query.js
- rebased to remove the batch feature from the branch (closed previous PR).
- the file as been reformatted automatically by VS (sorry), the real change is from line 232 to 272, in the function "buildCarousel" (start at 222).
=> No carousel on single image

src/main/webapp/js/components/interface/tutorial/Tutorial.js
=> use setState instead of mutating state directly in tutorial

src/main/webapp/js/components/interface/query/query.less
Ref https://github.com/VirtualFlyBrain/geppetto-vfb/issues/242#issuecomment-412081965
=> fix for overlapping content

src/main/webapp/js/components/interface/query/query.less
=> adding faint colour to differentiate for click off when few results

src/main/webapp/js/components/widgets/stackViewer/StackViewerComponent.js
Hot fix to prevent NaN being returned for image size
=> ignoring failed query html response pages

src/main/webapp/js/components/interface/spotlight/spotlight.less
Closes https://github.com/VirtualFlyBrain/geppetto-vfb/issues/245
=> Fix for clipping of spotlight buttons

src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterGUISync.js, src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterModelSync.js, src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterWidgetSync.js, src/main/webapp/js/pages/geppetto/GEPPETTO.Events.js, src/main/webapp/package.json
=> Migrate to latest jupyter libs

.travis.yml
=> fix npm gl failure

.travis.yml, src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
This one takes care of 
https://github.com/VirtualFlyBrain/geppetto-vfb/issues/246
https://github.com/VirtualFlyBrain/geppetto-vfb/issues/213
and improves 
https://github.com/VirtualFlyBrain/geppetto-vfb/issues/247
=> Selection bug fix and prevents selection if a mouse movement is detected

src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterUtils.js, src/main/webapp/js/geppettoProject/ProjectsController.js
=> Fix caspertest

src/main/webapp/js/components/widgets/WidgetCapability.js, src/main/webapp/js/components/widgets/popup/Popup.js, src/main/webapp/js/components/widgets/popup/Popup.less, src/main/webapp/package.json
New term info component.
- Resize has not been taken into account since there is a separate card for the whole VFB UI.
- Casper tests to be fixed (done soon).
=> New term info

src/main/webapp/package.json
@ddelpiano keeping latest Virgo (which is used on v2-dev.VirtualFlyBrain.org) in sync
=> add dependencies

src/main/webapp/js/communication/geppettoJupyter/PythonControlledCapability.js
=> Flickering issue

src/main/webapp/js/communication/geppettoJupyter/GeppettoJupyterUtils.js, src/main/webapp/js/communication/geppettoJupyter/PythonControlledCapability.js
=> Issue 79 2

src/main/webapp/js/communication/MessageSocket.js, src/main/webapp/js/pages/geppetto/GEPPETTO.Events.js
=> create event for when websocket is disconnected

.travis.yml, src/main/webapp/package.json
Adds library for taking screenshots
=> Screenshot feature

src/main/webapp/package.json, src/main/webapp/webpack.config.js
- Adds react-dropzone dependency
- Adds jsx extension to webpack
- Freezes material-ui version
=> HNN dependencies

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
=> Development selection fix

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
Reverts openworm/org.geppetto.frontend#860
=> Revert "Development selection fix"

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
=> compute bounding box

src/main/webapp/js/components/widgets/plot/Plot.js, src/main/webapp/package.json
=> update plotly axes title deprecated attr

src/main/webapp/js/pages/geppetto/GEPPETTO.Main.js, src/main/webapp/js/pages/geppetto/geppetto.ejs, src/main/webapp/webpack.config.js
=> Jupyter hub

src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js
see three.modules.js line 40730 intersects.sort( ascSort );
- [NA] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
=> List is already sorted by distance in THREE.Raycaster.intersectObjects

src/main/webapp/webpack.config.js
the publicPath was resolved to "/" for contextPath == "/" instead of "/geppetto/build"
=> fix path.join in webpack

src/main/webapp/style/less/components/flexLayout.less, src/main/webapp/style/less/main.less
Flex Layout style added to geppetto.
=> FlexLayout style added to geppetto

src/main/java/org/geppetto/frontend/dashboard/service/UserResource.java, src/main/webapp/js/components/widgets/connectivity/forces.js
=> splitting my old frontend and client stuff

.travis.yml, README.md
=> Patch: Permissive dependency on geppetto bundles [1.0,2.0)
